---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: check-added-large-files
    - id: check-json
    - id: check-yaml
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0

  - hooks:
    - args: [--fix, --exit-non-zero-on-fix]
      id: ruff
    - id: ruff-format
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4

  # Markdown linting
  - hooks:
    - args: ["--fix"]  # Automatically fix what it can
      id: markdownlint
    repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
...
